# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.11.0
      - image: cimg/redis:7.0.5
    steps:
      - checkout
      - run: npm install
      - run: npm run tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
